# Generated by Django 5.0.6 on 2026-07-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
