# Generated by Django 5.0.6 on 2026-07-10 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_importconfig_excelimport_nom_fichier_origine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele_analyste', models.CharField(blank=True, max_length=100)),
                ('modele_chat', models.CharField(blank=True, max_length=100)),
                ('modele_orchestrateur', models.CharField(blank=True, max_length=100)),
                ('timeout_secondes', models.PositiveIntegerField(default=60)),
                ('max_iterations', models.PositiveIntegerField(default=5)),
                ('analyste_destinataires', models.JSONField(blank=True, default=list, help_text="Emails fixes, 'departement:X', ou 'tous' — qui reçoit les alertes de l'agent analyste.")),
            ],
        ),
        migrations.CreateModel(
            name='AgentAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField(blank=True)),
                ('decisions', models.JSONField(blank=True, default=list)),
                ('alertes_envoyees', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excel_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_agent', to='core.excelimport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'Utilisateur'), ('ASSISTANT', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('outils_utilises', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_workflow', models.CharField(choices=[('FIN_DE_MOIS', 'Fin de mois'), ('ONBOARDING', 'Onboarding'), ('AUDIT_CONTRATS', 'Audit contrats'), ('RAPPORT_HEBDO', 'Rapport hebdo'), ('PERSONNALISE', 'Personnalisé')], max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('etapes', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ECHEC', 'Échec')], default='EN_COURS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_lances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
