# Generated by Django 5.0.6 on 2026-07-10 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatisations', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteEnvoyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_jours', models.IntegerField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_envoyees', to='employees.contract')),
                ('regle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='automatisations.regleautomatisation')),
            ],
            options={
                'ordering': ['-date_envoi'],
                'unique_together': {('regle', 'contract', 'delai_jours')},
            },
        ),
    ]
