# Generated by Django 5.0.6 on 2026-07-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatisations', '0002_alerteenvoyee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('fichier', models.FileField(upload_to='surveillance/')),
                ('frequence', models.CharField(choices=[('HORAIRE', 'Toutes les heures'), ('QUOTIDIEN', 'Quotidien')], default='QUOTIDIEN', max_length=10)),
                ('heure_quotidienne', models.TimeField(default='09:00')),
                ('prompt_analyse', models.TextField(help_text="Ce qu'Ollama doit chercher/faire avec le contenu du document.")),
                ('mode_envoi', models.CharField(choices=[('TOUJOURS', 'Toujours (rapport périodique)'), ('ANOMALIE', 'Seulement si anomalie détectée')], default='ANOMALIE', max_length=10)),
                ('destinataires', models.JSONField(blank=True, default=list, help_text="Emails fixes, 'departement:X', ou 'tous'.")),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('derniere_execution', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envoye', models.BooleanField(default=False)),
                ('resume', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automatisations.tachesurveillance')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
