# Generated by Django 5.0.6 on 2026-07-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatisations', '0003_tachesurveillance_executionsurveillance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatisationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_global', models.TextField(blank=True)),
                ('heure_rapport_quotidien', models.TimeField(default='09:00')),
                ('dernier_rapport_envoye', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
