# Generated by Django 5.0.6 on 2026-07-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatisations', '0004_automatisationconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='regleautomatisation',
            name='format',
            field=models.CharField(choices=[('TEXTE', 'Texte brut'), ('HTML', 'HTML')], default='TEXTE', max_length=10),
        ),
    ]
