# Generated by Django 5.0.6 on 2026-07-12 16:39

import django.db.models.deletion
from django.db import migrations, models


def backfill_cle_dedup(apps, schema_editor):
    AlerteEnvoyee = apps.get_model('automatisations', 'AlerteEnvoyee')
    for alerte in AlerteEnvoyee.objects.all():
        alerte.cle_dedup = f"contrat:{alerte.contract_id}:{alerte.delai_jours}"
        alerte.save(update_fields=['cle_dedup'])


class Migration(migrations.Migration):

    dependencies = [
        ('automatisations', '0006_regleautomatisation_cree_par_and_more'),
        ('employees', '0003_employee_donnees_supplementaires'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alerteenvoyee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alerteenvoyee',
            name='cle_dedup',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='regleautomatisation',
            name='champ_cible',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='regleautomatisation',
            name='operateur',
            field=models.CharField(blank=True, choices=[('INFERIEUR_A', 'Inférieur à'), ('SUPERIEUR_A', 'Supérieur à'), ('EGAL', 'Égal à'), ('CONTIENT', 'Contient'), ('VIDE', 'Est vide / absent')], max_length=20),
        ),
        migrations.AddField(
            model_name='regleautomatisation',
            name='type_condition',
            field=models.CharField(choices=[('CONTRAT', 'Contrat expirant'), ('CHAMP_PERSONNALISE', 'Champ personnalisé')], default='CONTRAT', max_length=20),
        ),
        migrations.AddField(
            model_name='regleautomatisation',
            name='valeur_seuil',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='alerteenvoyee',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes_envoyees', to='employees.contract'),
        ),
        migrations.AlterField(
            model_name='alerteenvoyee',
            name='delai_jours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_cle_dedup, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='alerteenvoyee',
            unique_together={('regle', 'cle_dedup')},
        ),
    ]
