# Generated by Django 5.0.6 on 2026-07-12 16:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_employee(apps, schema_editor):
    AlerteEnvoyee = apps.get_model('automatisations', 'AlerteEnvoyee')
    for alerte in AlerteEnvoyee.objects.filter(contract__isnull=False, employee__isnull=True):
        alerte.employee_id = alerte.contract.employee_id
        alerte.save(update_fields=['employee'])


class Migration(migrations.Migration):

    dependencies = [
        ('automatisations', '0007_alter_alerteenvoyee_unique_together_and_more'),
        ('employees', '0003_employee_donnees_supplementaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerteenvoyee',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes_recues', to='employees.employee'),
        ),
        migrations.RunPython(backfill_employee, migrations.RunPython.noop),
    ]
