# Generated by Django 5.0.6 on 2026-07-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_categorie_employee_date_fin_contrat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='donnees_supplementaires',
            field=models.JSONField(blank=True, default=dict, help_text="Colonnes Excel importées qui ne correspondent à aucun champ système — HR data n'est pas limité aux contrats (congés, formations, évaluations, etc.)."),
        ),
    ]
