# Generated by Django 5.0.6 on 2026-07-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='imports/')),
                ('status', models.CharField(choices=[('PENDING', 'En cours'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], default='PENDING', max_length=10)),
                ('lignes_total', models.PositiveIntegerField(default=0)),
                ('lignes_importees', models.PositiveIntegerField(default=0)),
                ('lignes_erreurs', models.PositiveIntegerField(default=0)),
                ('erreurs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
