# Generated by Django 5.0.6 on 2026-07-10 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automatisations', '0002_alerteenvoyee'),
        ('core', '0002_maillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='bcc',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maillog',
            name='cc',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='maillog',
            name='format',
            field=models.CharField(choices=[('TEXTE', 'Texte'), ('HTML', 'HTML')], default='TEXTE', max_length=10),
        ),
        migrations.AddField(
            model_name='maillog',
            name='regle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to='automatisations.regleautomatisation'),
        ),
    ]
