# Generated by Django 5.0.6 on 2026-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_maillog_bcc_maillog_cc_maillog_format_maillog_regle'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='destinataire_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='maillog',
            name='destinataire_nom',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
