# Generated by Django 5.0.6 on 2026-07-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maillog_destinataire_email_maillog_destinataire_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', models.JSONField(blank=True, default=dict, help_text='system_field -> excel column header (lowercase)')),
                ('dossier_surveille', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='excelimport',
            name='nom_fichier_origine',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='excelimport',
            name='source',
            field=models.CharField(choices=[('UPLOAD', 'Upload manuel'), ('DOSSIER', 'Dossier surveillé')], default='UPLOAD', max_length=10),
        ),
    ]
