# Generated by Django 5.0.6 on 2026-07-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_excelimport_cree_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur')], max_length=10)),
                ('logger_name', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_techni_created_80fb0b_idx'), models.Index(fields=['level'], name='core_techni_level_e2cb9f_idx')],
            },
        ),
    ]
